# Translations template for keystone.
# Copyright (C) 2014 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: Keystone\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/keystone\n"
"POT-Creation-Date: 2014-08-04 06:06+0000\n"
"PO-Revision-Date: 2014-07-16 14:42+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Vietnamese (Viet Nam) (http://www.transifex.com/projects/p/"
"keystone/language/vi_VN/)\n"
"Language: vi_VN\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: keystone/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "Ngoại lệ ban đầu được giảm xuống: %s"

#: keystone/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "Ngoại lệ bất ngờ xảy ra %d thời gian(s) ... thử lại"

#: keystone/openstack/common/lockutils.py:119
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr "Không thể nhả ra khóa đã bị chiếm dụng `%s`"

#: keystone/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr "trong cuộc gọi vòng lặp thời khoảng cố định "

#: keystone/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr "trong cuộc gọi lặp động"

#: keystone/openstack/common/policy.py:507
#, python-format
msgid "Failed to understand rule %s"
msgstr "Không hiểu luật %s"

#: keystone/openstack/common/policy.py:517
#, python-format
msgid "No handler for matches of kind %s"
msgstr "Không có bộ xử lý thích ứng của loại %s"

#: keystone/openstack/common/policy.py:787
#, python-format
msgid "Failed to understand rule %r"
msgstr "Không hiểu luật %r"

#: keystone/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr "Ngoại lệ trong quá trình dọn dẹp RPC"

#: keystone/openstack/common/service.py:277
msgid "Unhandled exception"
msgstr "ngoại lệ không được quản lý"
